spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

app.s3.bucket-name=${AWS_S3_BUCKET_NAME:dev-bucket}
app.s3.region=${AWS_S3_REGION}
app.s3.url-expiration-minutes=${AWS_S3_URL_EXPIRATION_MINUTES:15}

spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}